all:
	# g++ bench_sender.cc ../../build/lib/libmessage_lib.so \
	# 	-o bench_sender -Wall -I../../src/communication/lib/include/
	# g++ bench_receiver.cc ../../build/lib/libmessage_lib.so \
	# 	-o bench_receiver -Wall -I../../src/communication/lib/include/
	g++ message_bench.cc \
		-g -o message_bench -Wall
